steps:
  - label: "autoformat"
    plugins:
      - docker-compose#v4.9.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          command: [".buildkite/scripts/autoformat.sh"]

  - label: "test"
    plugins:
      - docker-compose#v4.9.0:
          run: tooling
          command: ["yarn", "test"]

  - block: "Package and deploy :rocket:"

  - label: "deploy"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::760097843905:role/platform-ci"
      - docker-compose#v4.9.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          command: [".buildkite/scripts/deploy.sh"]
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_DEFAULT_REGION=eu-west-1
